### ISSUE TITLE
[iOS] Fonts are fat at the first start of the app

### ISSUE THREAD

**Issue by micuintus** [micuintus/harbour-Berlin-Vegan#110]
![img_0007](https://user-images.githubusercontent.com/8768660/28747696-5812d7ce-74a5-11e7-89c4-fc4e806454e6.PNG)
![img_0005](https://user-images.githubusercontent.com/8768660/28747697-5815e3ec-74a5-11e7-973a-1639208e2320.PNG)

**Comment by micuintus** [comment]
@jmastr Close as won't fix?

**Comment by jmastr** [comment]
Couldn't reproduce it.
