### ISSUE TITLE
[iOS] Search bar is half broken: Sometimes the "x" to remove a query doesn't really react + the on screen keyboard doesn't piss off 

### ISSUE THREAD

**Issue by micuintus** [micuintus/harbour-Berlin-Vegan#113]
Didn't we have that issue b4? How did we fix it back then?

**Comment by jmastr** [comment]
There seems no easy way to fix the 'x' problem at the moment e.g. to expand the hit area, see:

https://v-play.net/doc/vplayapps-searchbar/

One has to hit exactly the 'x'.

**Comment by jmastr** [comment]
Maybe place a bug report at v-play?
