### ISSUE TITLE
[v-play] change the "get directions" icon to something more meaningful

### ISSUE THREAD

**Issue by jmastr** [micuintus/harbour-Berlin-Vegan#117]
Several beta testers complained, that they don't know how to get directions, and after I explained it, they suggested to place the icon into the IconToolBar.

**Comment by micuintus** [comment]
How many were these? :)
Hmm, I am still not too convinced that the icon bar is the right place for this. I kind of like the three icon style layout from the native Android app.

**Comment by jmastr** [comment]
Damn, you're right. I like that style too. Maybe we just exchange the icon to make it more clear to the users?
