### ISSUE TITLE
[v-play] Height in SectionHeader and DetailItem is too large 

### ISSUE THREAD

**Issue by micuintus** [micuintus/harbour-Berlin-Vegan#129]

**Comment by jmastr** [comment]
Could you describe (or put a picture) for more details?

**Comment by micuintus** [comment]
Sure.

Designer says:
![3_details_idee1](https://user-images.githubusercontent.com/11860038/28744276-6038c2da-745d-11e7-851b-6cf986bdb1eb.png)

Computer says: 
![img_0008](https://user-images.githubusercontent.com/8768660/29281519-a261bcba-811f-11e7-9b33-0ae28e581a8b.PNG)

**Comment by jmastr** [comment]
niz3!
