### ISSUE TITLE
Where-am-I icon is off

### ISSUE THREAD

**Issue by micuintus** [micuintus/harbour-Berlin-Vegan#131]
on Sailfish this is really strong when zooming out a lot, but also on iOS this is visible.

**Comment by jmastr** [comment]
Can you describe (or put some pictures) a little bit more in detail? Do you want to have the center of the circle aligned with the bottom of the venue marker, when zooming out a lot?

**Comment by micuintus** [comment]
Si si, if looken at twoe picture, you seeing dat middle of round blue circle is first under water, then, when zoomed out, over water:

![img_0011](https://user-images.githubusercontent.com/8768660/29281237-7ece069c-811e-11e7-904b-97a3cb3ebc3f.PNG)
![img_0012](https://user-images.githubusercontent.com/8768660/29281236-7ecb934e-811e-11e7-9269-2ac4c6094113.PNG)

**Comment by jmastr** [comment]
it's because the anchor point is middle bottom of outer circle. i'll take the ticket. is it correct on sailfish? i don't have sailfish with geo position.

**Comment by micuintus** [comment]
Unfortunatel yes :/

![20170815005618](https://user-images.githubusercontent.com/8768660/29295437-b471df68-8154-11e7-9595-cfe795e9718c.jpg)
![20170815005553](https://user-images.githubusercontent.com/8768660/29295438-b4764c2e-8154-11e7-8636-1bde9a50b7d7.jpg)
