### ISSUE TITLE
[v-play] Location marker's color broken when coming from VenueMapOverviewPage

### ISSUE THREAD

**Issue by jmastr** [micuintus/harbour-Berlin-Vegan#183]
Steps to reproduce:
- e.g. search for "Mana"
- click on the map overview icon
- click on the location marker
- click on "get directions"
- see that the location marker's color is red instead of green

What's working:
- e.g. search for "Mana"
- click on the list entry
- click on "get directions"
- see that the location marker's color is green

Expected behaviour:
- location marker's color has always the correct color

**Comment by micuintus** [comment]
Still exists…

**Comment by jmastr** [comment]
Cannot reproduce. Could you give more info like commit, steps to reproduce, etc.

**Comment by micuintus** [comment]
Ignore me, I am sorry, I meant to reopen #185 instead…
