### ISSUE TITLE
Show venue sub type in venue description

### ISSUE THREAD

**Issue by micuintus** [micuintus/harbour-Berlin-Vegan#190]
For food venues:
- Restaurant
- Cafe
- Imbiss
- Eiscafe

For shopping venues:
-  Eis
-  Drogerie
-  Bio
-  Backwaren
-  Kleidung

**Comment by jmastr** [comment]
@micuintus It is done for Food. Do we really wanna do it for Shopping as well?

**Comment by micuintus** [comment]
Duplicate of #290
