### ISSUE TITLE
[iOS] iPhone X support

### ISSUE THREAD

**Issue by fassko** [micuintus/harbour-Berlin-Vegan#211]
Tab bar on iPhone X is under the home indicator.

Sadly app isn't native otherwise I would like to contribute.

![img_0705](https://user-images.githubusercontent.com/29482/37295563-2a5a8916-2621-11e8-903b-79b030d340c8.PNG)

**Comment by fassko** [comment]
@jmastr Hard to say as I don't have any experience with tools that you're using. Maybe updating the libraries which are used to make the ui would solve the this issue. It works, just round corners and home indicator hides the tab bar.

P.S. I'm moving to Berlin for two months and as I'm vegan myself found this nice app. ;)

**Comment by jmastr** [comment]
@fassko that's why i asked what a native developer would need to do to support iPhone X. But I also asked at the framework's forum: https://v-play.net/developers/forums/t/iphone-x-support-2

Glad to hear that :)

**Comment by fassko** [comment]
If you use native tools then it should support out of the box. At least it did for me. Just need to rebuild using new iOS SDK.

Anyway if you need help with native iOS stuff just ask. I'm iOS Developer myself.

**Comment by jmastr** [comment]
Great, we will do that if necessary.

Got a response in the mentioned request: we need to wait for the next SDK version.

**Comment by micuintus** [comment]
Cool, thanks @fassko also from my side for reporting this issue.
Thinking out loud: If rebuilding with the new iOS SDK only doesn't solve it,
maybe also using the new V-Play SDK helps?

Is that somehow related or is there another issue with the iPhoneX?
https://v-play.net/developers/forums/t/iphone-x-support

**Comment by micuintus** [comment]
What is https://v-play.net/developers/forums/t/iphone-x-support about?

**Comment by fassko** [comment]
I have no experience with this v-play platform and Qt at all. But as far as I understand need to set iPhone X launch screen in Assets file.

In native iOS development launch images will be deprecated so I don't know actually how this will work in future.
But anyway create a launch screen with iPhone X needed resolution and add to assets and try to build it with iPhone X simulator.

**Comment by fassko** [comment]
Another issue I found out with iPhone X. After rotating to landscape and back top navigation bar is screwed. Does this app needs rotating functionality? I guess for iPad.

![img_0712](https://user-images.githubusercontent.com/29482/37467132-2245cfc6-2868-11e8-9591-40e54b74be5f.png)

**Comment by jmastr** [comment]
<img width="517" alt="bildschirmfoto 2018-04-14 um 09 49 38" src="https://user-images.githubusercontent.com/11860038/38765843-6729b1a2-3fc9-11e8-8d6d-91216ab55a82.png">

V-Play 2.16.0 was released and they have iPhone X support. Stay tuned.

**Comment by jmastr** [comment]
New app version submitted and waiting for review.

**Comment by jmastr** [comment]
Fixed in version 3.3.
