### ISSUE TITLE
Fix truncation broken by #214

### ISSUE THREAD

**Issue by jmastr** [micuintus/harbour-Berlin-Vegan#215]
<img width="545" alt="screen shot 2018-03-21 at 21 36 38" src="https://user-images.githubusercontent.com/11860038/37736033-0f8208cc-2d50-11e8-8923-b7d3552eacee.png">

Truncation is broken for `Minh Huy`, because it is still open, but the space is reserved for `closed at the moment`.

**Comment by micuintus** [comment]
FYI: I did some experiments with ```QtQuick.Layouts```. Using them radically simplifies the code. Unfortunately, I couldn't get them running properly on Sailfish --- even if don't use margins with layouts. It seems, we have to park the branch ([micu/fix_truncation_#215_layouts](/micuintus/harbour-Berlin-Vegan/tree/micu/fix_truncation_%23215_layouts)) until Jolla decides to finally update Sailfish to a proper Qt version, which will happen with Sailfish 3, sometime later this year...
