### ISSUE TITLE
Ask people to tell owners/waiters that they found their venue via BV

### ISSUE THREAD

**Issue by micuintus** [micuintus/harbour-Berlin-Vegan#233]
Sometimes venue owners aren't aware how important it is to be present on platforms like BVApp (or happy cow, etc.)

**Comment by micuintus** [comment]
An idea is to this via notifications

**Comment by micuintus** [comment]
https://sailfishos.org/develop/docs/nemo-qml-plugin-notifications/qml-nemo-notifications-notification.html/

https://v-play.net/doc/plugin-notification/#example-usage

**Comment by micuintus** [comment]
![screenshot_20180901_172717](https://user-images.githubusercontent.com/8768660/44947375-a3751500-ae0c-11e8-9d82-0be805f8e51d.png)

**Comment by jmastr** [comment]
How about a popup after `x` times opening the app?
