### ISSUE TITLE
[Android] Add header picture to Android menu

### ISSUE THREAD

**Issue by micuintus** [micuintus/harbour-Berlin-Vegan#260]

**Comment by jmastr** [comment]
From which profile exactly? BV doesn’t have a user management and therefore we don’t have profile pictures of our users. I am wondering which pictures you want to show...

**Comment by micuintus** [comment]
What I mean is this header picture in the Android menu, in V-Play they call it ```AppDrawer```:
https://v-play.net/doc/vplayapps-navigation/#headerView-prop
