### ISSUE TITLE
Add filter options

### ISSUE THREAD

**Issue by micuintus** [micuintus/harbour-Berlin-Vegan#31]
- vegan category
- accessibility
- etc.

Code wise we should use ```QFlags``` for that which we can set as filter conditions to our ```VenueSortFilterProxyModel``` (once the #42 is merged).

**Comment by jmastr** [comment]
We should display the number of found gastro venues / shopping venues after a filter is applied.

**Comment by micuintus** [comment]
Closing this issue, tracking the remaining missing filter options in #173
