### ISSUE TITLE
F-Droid listing

### ISSUE THREAD

**Issue by IzzySoft** [micuintus/harbour-Berlin-Vegan#321]
As this app uses the same package name as its "former Android version": is it intended as a direct (drop-in) replacement? Or is it rather a fork? Asking because the former one is listed on F-Droid and was last updated in February. So should we see if we can switch to this new repo? Or would you rather switch to a new package name for a separate listing?

**Comment by jmastr** [comment]
@IzzySoft it is meant as a direct drop-in like on other platforms e.g. iOS. However we use a close source framework called Felgo, so there is no way to get that version into F-Droid. The „old“ Android app (2.x) is not maintained anymore and replaced by this app (3.x). 

Does that answer your question?

**Comment by IzzySoft** [comment]
@jmastr thanks and yes, this perfectly answers my question – though not exactly as I hoped…

As the app itself is still under a FOSS license (GPL-2.0), maybe I can offer a "middle way": If you could provide the APKs (e.g. attaching them to `releases/`), I could serve them via [my repo](https://apt.izzysoft.de/fdroid/). I'd then update the app description(s) accordingly so it's clear what's going on. Wouldn't be the first app dealt with this way (see e.g. FBReader).

**Comment by jmastr** [comment]
@micuintus Could you provide the APK?

**Comment by micuintus** [comment]
> As the app itself is still under a FOSS license (GPL-2.0), maybe I can offer a "middle way": If you could provide the APKs (e.g. attaching them to releases/), I could serve them via my repo. I'd then update the app description(s) accordingly so it's clear what's going on. Wouldn't be the first app dealt with this way (see e.g. FBReader).

@IzzySoft Cool, that'll be amazing! Thanks for the offer!

@jmastr: Done -> 
https://github.com/micuintus/harbour-Berlin-Vegan/releases/tag/3.5.1

**Comment by IzzySoft** [comment]
@micuintus Thanks, done! Will [turn up here](https://apt.izzysoft.de/fdroid/index/apk/org.berlin_vegan.bvapp) with tomorrow's sync (in about 23 hours; just missed today's sync by a few minutes).

I've also [created a MR at F-Droid](https://gitlab.com/fdroid/fdroiddata/merge_requests/6174) to include the hint into the description there as well. I've not seen that 3rd-party-repos (like mine) are referenced from descriptions in the official repo – so though I'm one of the maintainers myself, I didn't merge that yet but prefer waiting for one more maintainer (and the owner) to approve; IMHO that's a decent thing to do.

Furthermore: my repo running on "private resources" (without any funding; donations, if there are any coming in, do not even remotely cover costs), I've limited the listing to a single architecture – picking the ARMv7 build (that should cover ~90% AFAIK). Updates will be fetched automatically within 24h of your tagging a release and having an `*armv7*.apk` attached to it.

Hope that makes everyone happ(y|ier) now :smile: I'm proud being able to contribute to a great project this way!

PS: Why not pointing out from the README where to get the app (i.e. links to AppStore, Play Store etc)? Feel free to include a link to my repo then as well :wink:

If there are any questions, don't hesitate asking. I'm closing this issue now; though not solved by updating the official repo, this is as far as we can get this currently. If you think otherwise, just reopen.

Thanks again!
