### ISSUE TITLE
Port to iOS

### ISSUE THREAD

**Issue by micuintus** [micuintus/harbour-Berlin-Vegan#48]
This is just an idea ATM! Maybe a first approach should be started after 1.0 4 Sailfish is out?

Maybe with the help of
https://github.com/M4rtinK/universal-components or
https://v-play.net/ (or even both: add v play as a backend for UC)?

Qt iOS ressources:
-------------------
https://conf.qtcon.org/en/qtcon/public/events/409
http://www.codingsubmarine.com/qt-on-ios-and-android-looking-native-today-or-maybe-tomorrow/
https://www.youtube.com/watch?v=8A7DPUwIcDg

https://github.com/V-Play/QtWorldSummit2016-V-Play
http://doc-snapshots.qt.io/qt5-5.8/qtlabsplatform-index.html

Qt iOS without the help of V-Play
---------------------------------
http://www.codingsubmarine.com/qt-on-ios-and-android-looking-native-today-or-maybe-tomorrow/
https://github.com/amarchen/CuteContacts-iOS
http://www.codingsubmarine.com/cutecontacts-ios7-cloning-ios7-contacts-application-ui-in-qtqml/

**Comment by micuintus** [comment]
FYI:
https://together.jolla.com/question/131120/survey-supporting-to-port-v-play-to-sailfish/
https://together.jolla.com/question/71520/request-qtquick-controls/
https://fruct.org/sites/default/files/files/conference19/3_EmergingT_I/1_Cross-Platform_Development_Sailfish.pdf

https://together.jolla.com/question/121167/its-faster-to-develop-for-android-than-sailfish/

https://github.com/lirios/fluid/tree/develop/controls

https://www.google.de/search?q=Qt+Quick+Controls&ie=utf-8&oe=utf-8&client=firefox-b&gfe_rd=cr&ei=jbtSWNjSEaLH8AfA7Y-ABg#q=(Jolla+OR+%22sailfish+OS%22)+AND+%22Qt+Quick+Controls%22

https://www.google.de/search?q=Sailfish+Silca&ie=utf-8&oe=utf-8&client=firefox-b&gfe_rd=cr&ei=7rxSWKjoM7DH8Aeh_oioDA#q=Sailfish+Silica+for+Android

**Comment by micuintus** [comment]
#ifdef for QML:

https://katastrophos.net/andre/blog/2013/09/20/qml-preprocessor-the-qnd-and-kiss-way/
http://blog.qt.io/blog/2017/02/06/native-look-feel/#comment-1198954
https://forum.qt.io/topic/5739/platform-specific-part-of-qml-file
https://forum.qt.io/topic/1639/ifdef-mac-win-linux-in-qml/9

**Comment by jmastr** [comment]
![photo 17 08 17 06 41 33](https://user-images.githubusercontent.com/11860038/29399106-27830e8a-8328-11e7-84d5-18fbc0f18b8a.png)

WE DID IT! We made it to the Apple App Store!
