### ISSUE TITLE
Provide a setting to configure whether automatic sorting is being conducted

### ISSUE THREAD

**Issue by micuintus** [micuintus/harbour-Berlin-Vegan#49]
With a fix for #45 in place, we need an option to let the user decide whether they want to have this 
automatic sorting in place or not. In the case the automatic sorting is disabled, they need the "Update sorting" menu entry back.

**Comment by micuintus** [comment]
@jmastr Is such a thing even desired (i.e. disabling sorting update)?

**Comment by jmastr** [comment]
No, we want it to sort automatically. Everything else can be handled via the search field.
