### ISSUE TITLE
Map overview

### ISSUE THREAD

**Issue by micuintus** [micuintus/harbour-Berlin-Vegan#7]
-> QtLocation map?
-> Maep?
-> harbour-mapp? --> https://github.com/unsanded/harbour-mapp
-> poor maps? https://github.com/otsaloma/poor-maps
-> https://together.jolla.com/question/51587/a-map-component-for-sailfish-apps/

**Comment by micuintus** [comment]
https://github.com/b0bben/SailfishOS_MapTutorial

**Comment by jmastr** [comment]
Can I close this issue since #148 is merged and we have #149?

**Comment by micuintus** [comment]
Yeah, please lets close this guy.
