### ISSUE TITLE
[v-play] Favorite state does not sync if the same venue entry is open twice

### ISSUE THREAD

**Issue by micuintus** [micuintus/harbour-Berlin-Vegan#87]
Steps to reproduce:
1. Open an a venue entry, e.g. in the Food list
2. Favorite it
3. Go to the Favorites tab and open it there
4. Unfavorite it there
5. Go back to the Food list
Observed result: Entry is still shown as Favorite in the Food tab

---

1. A solution would be using a reference in the ```VenueDescription``` or some index based direct access, but we would need to make sure that the resorting does not swap out our currently opened entry.
2. A workaround would be always going back to the list view once you switch to a different tab. This might be more desirable UX wise anyway?

**Comment by jmastr** [comment]
I vote for solution 2. It is a workaround, but I'd like to see that user experience anyways.
