### ISSUE TITLE
Clarify situation that many venue entries do not have a picture

### ISSUE THREAD

**Issue by jmastr** [micuintus/harbour-Berlin-Vegan#93]
Currently the space is just blank.

**Comment by jmastr** [comment]
@micuintus is talking to our designer Robin, if we he can come up with some placeholder image, otherwise we will implement following solution:

![2_menue-ohnebild](https://user-images.githubusercontent.com/11860038/28744251-f258970e-745c-11e7-997f-5ad8d942bb02.png)

**Comment by jmastr** [comment]
We got a placeholder image from our designer <3

**Comment by jmastr** [comment]
Original:

![original](https://user-images.githubusercontent.com/11860038/29091924-bde7f0d4-7c84-11e7-8de5-3b45560b726d.png)

50px moved:

![plus50](https://user-images.githubusercontent.com/11860038/29091933-c1ca87fc-7c84-11e7-8d8d-b6a52293b1c8.png)

100px moved:

![plus100](https://user-images.githubusercontent.com/11860038/29091938-c5f65c02-7c84-11e7-83fd-85ff4ceec163.png)

**Comment by jmastr** [comment]
@micuintus what do you think? i like the 100px...

**Comment by micuintus** [comment]
9000km!? Are you in the US somewhere? Or flying over Berlin with a satellite?

**Comment by micuintus** [comment]
VERY VERY HOT!

All three are fine. I guess my order would be 50px, then 0, then 100px. ;)

**Comment by jmastr** [comment]
From the mailing list: 50px it is.

**Comment by jmastr** [comment]
With #123 we do not need an adapted image anymore, but can use the original from our designer.
